language: ruby

rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.2

gemfile:
  - Gemfile_ar41
  - Gemfile_ar50
  - Gemfile_ar51
  - Gemfile_ar_master

matrix:
  fast_finish: true
  allow_failures:
    - rvm: 2.4.6
      gemfile: Gemfile_ar_master
    - rvm: 2.5.5
      gemfile: Gemfile_ar_master
    - rvm: 2.6.2
      gemfile: Gemfile_ar_master
