on:
  workflow_dispatch: ~
  schedule:
    - cron: "0 0 1 3,6,9,12 *" # At 00:00 on 1st of March, June, September, and December

name: API update reminder
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/api_update_reminder.md
