on:
  workflow_dispatch: ~
  schedule:
    - cron: "0 0 1 1,4,7,10 *" # At 00:00 on 1st of January, April, July, and October

name: API update reminder on release
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: JasonEtco/create-an-issue@1b14a70e4d8dc185e5cc76d3bec9eab20257b2c5 # v2.9.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/api_update_reminder_on_release.md
