name: CI

on:
  - push
  - pull_request

jobs:
  build:
    name: Ruby ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 3.2
          - 3.3
          - 3.4
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@ab177d40ee5483edb974554986f56b33477e21d0 # v1.265.0
        with:
          ruby-version: ${{ matrix.version }}
      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
      - name: Run Bundle Commands
        run: |
          bundle config set --with docs
          bundle config set ignore_messages true
          bundle
      - name: Run RuboCop
        run: |
          bundle exec rubocop
      - name: Run Typecheck
        run: |
          bundle exec srb tc
      - name: Run tests
        run: |
          bundle exec rake test:library
      - name: Run REST wrapper tests
        run: |
          bundle exec rake test:rest_wrappers
