name: CI

on:
  - push
  - pull_request

jobs:
  build:
    name: Ruby ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 3.0
          - 3.1
          - 3.2
          - 3.3
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@bb6434c747fa7022e12fa1cae2a0951fcffcff26 # v1.253.0
        with:
          ruby-version: ${{ matrix.version }}
      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
      - name: Run Bundle Commands
        run: |
          bundle config set --with docs
          bundle config set ignore_messages true
          bundle
      - name: Run RuboCop
        run: |
          bundle exec rubocop
      - name: Run Typecheck
        run: |
          bundle exec srb tc
      - name: Run tests
        run: |
          bundle exec rake test:library
      - name: Run REST wrapper tests
        run: |
          bundle exec rake test:rest_wrappers
